services:
  dev:
    build: .
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/run/user/1000/wayland-0:/run/user/1000/wayland-0
    working_dir: /app
    environment:
      env: docker
      LD_LIBRARY_PATH: /app/target/debug/deps
      # WAYLAND_DISPLAY: wayland-0
      # XDG_RUNTIME_DIR: /run/user/1000
    # ipc: host
    # devices:
    #   - /dev/dri:/dev/dri

volumes:
  cargo-cache:
