name: CI

on:
  pull_request:
  push:
    branches:
      - trunk

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Install c libs
        run: sudo apt install -y libdbus-1-dev pkg-config
      - uses: actions/checkout@v6
      - name: Install Rust
        run: rustup update stable
      - name: run tests
        run: cargo test

  lint:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Install c libs
        run: sudo apt install -y libdbus-1-dev pkg-config
      - uses: actions/checkout@v6
      - name: Install Rust
        run: rustup update stable
      - name: fmt
        run: cargo fmt --check
      - name: clippy
        run: cargo clippy --all-targets --no-deps -- -D warnings


  analysis:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Install c libs
        run: sudo apt install -y libdbus-1-dev pkg-config
      - uses: actions/checkout@v6
      - name: Install Rust
        run: rustup default nightly
      - name: install machete
        run: cargo install cargo-machete
      - name: run machete
        run: cargo machete
      - name: install careful
        run: cargo install cargo-careful
      - name: setup careful
        run: cargo careful setup
      - name: run careful
        run: cargo careful test


  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Install c libs
        run: sudo apt install -y libdbus-1-dev pkg-config
      - uses: actions/checkout@v6
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
