name: Release

on:
  release:
    types:
      - published
    branches:
      - trunk

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Install c libs
        run: sudo apt install -y libdbus-1-dev pkg-config
      - uses: actions/checkout@v6
      - name: Install Rust
        run: rustup update stable
      - name: publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}

